apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yz3kixfkd-go
  janus-idp.io/tekton: yz3kixfkd-go
  backstage.io/kubernetes-id: yz3kixfkd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yz3kixfkd-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
